server:
  port: 3344
  
spring:
  application:
    name: microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/antonio-hao/microservice-config.git #GitHub上面的git仓库名字
          search-paths:
          - antonioMicroserviceConfig 
      label: master
          
